---
# install
- when: 
  - un_install_state == "present"
  - un_install_desktop != None
  block:

  # mkdir
  - name: Mkdir {{ un_install_desktop_dst | dirname }}
    become: true
    ansible.builtin.file:
      state: directory
      path: "{{ un_install_desktop_dst | dirname }}"
      owner: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root'}}"
      group: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root'}}"
      mode: u=rwx,g=r,o=r

  - name: Template desktop file {{ un_install_desktop_dst }}
    become: true
    ansible.builtin.template:
      src: "{{ role_path }}/files/{{ un_install_app }}/{{ un_install_desktop }}"
      dest: "{{ un_install_desktop_dst }}"
      owner: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root'}}"
      group: "{{ un_install_user if un_install_desktop_dst.startswith('/home/') else 'root'}}"
      mode: u=rw,g=,o=r

# remove
- when: un_install_state == "absent"
  block:

  - when:
    - un_install_desktop_dst != None
    - un_install_app in un_install_desktop_dst
    name: Remove {{ un_install_desktop_dst }}
    become: true
    ansible.builtin.file:
      path: "{{ un_install_desktop_dst }}"
      state: absent
